apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30105 
  selector:
    app.kubernetes.io/name: argocd-server
