apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-volume
  namespace: gitlab
  labels:
    volume-type: "gitlab"  
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /data/gitlab
