apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-gitlab
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  selector:
      matchLabels:
        volume-type: "gitlab"