apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-volume
  labels:
    volume-type: "httpd"  
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /confs/pvolume
