apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42-depl
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app42
  template:
    metadata:
      labels:
        app: app42
    spec:
      containers:
        - name: app42
          image: bitnami/grafana:11.5.0
          ports:
            - containerPort: 3000
