apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: traefik-ingress-rolebinding
 namespace: argocd
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: traefik-ingress-role
subjects:
 - kind: ServiceAccount
   name: traefik
   namespace: traefik