apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-depl
  namespace: argocd
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.6.15
          ports:
            - containerPort: 8080
