apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30105 
  selector:
    label: argocd
