apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-httpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path
  selector:
      matchLabels:
        volume-type: "httpd"