global:
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  hosts:
    domain: "localhost"
    https: false

gitlab-runner:
  install: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab:
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 250m
