apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-gitlab
  # namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path
  volumeName: gitlab-volume
  # selector:
  #     matchLabels:
  #       volume-type: "gitlab"