global:
  ingress:
    configureCertmanager: false
    class: "nginx"
    tls:
      enabled: false
  hosts:
    domain: "localhost"
    https: false
  rails:
    bootsnap:
      enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

postgresql:
  persistence:
    enabled: true
    existingClaim: pvc-vol-gitlab
    size: 256Mi

redis:
  persistence:
    enabled: true
    existingClaim: pvc-vol-gitlab

gitlab:
  toolbox:
    enabled : true
    persistence:
      enabled: true
      existingClaim: pvc-vol-gitlab
