global:
  ingress:
    configureCertmanager: false
    class: "nginx"
    tls:
      enabled: false
  hosts:
    domain: "localhost"
    https: false
  rails:
    bootsnap:
      enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

gitlab:
  gitaly:
    persistence:
      storageClass: standard
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
  registry:
    enabled: false
  minio:
    enabled: false
  prometheus:
    install: false
  gitlab-runner:
    install: false