global:
  ingress:
    configureCertmanager: false
    class: "nginx"
    tls:
      enabled: false
  hosts:
    domain: "localhost"
    https: false
  rails:
    bootsnap:
      enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

gitlab:
  redis:
    minReplicas: 1
    maxReplicas: 1
  postgres:
    minReplicas: 1
    maxReplicas: 1
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  registry:
    hpa:
      minReplicas: 1
      maxReplicas: 1
