apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: traefik-ingress-role
 namespace: argocd
rules:
 - apiGroups: ["networking.k8s.io"]
   resources: ["ingresses"]
   verbs: ["get", "list", "watch"]
 - apiGroups: [""]
   resources: ["services", "endpoints"]
   verbs: ["get", "list", "watch"]